### ISSUE TITLE
SPLIT INTO SMALL TICKETS: Create Shiny app for NDVI solution from Ecoscope

### ISSUE THREAD

**Issue by JudithDekkers** [SensingClues/Biodiversity-monitoring#1]
needs a new repository "Biodiversity monitoring"
this repo is created (open & GNLU Affero v3 licence)

**Comment by JudithDekkers** [comment]
will we build it in R or Python?
for this app we choose R

**Comment by JudithDekkers** [comment]
action for Melanie & Judith to split this ticket into smaller tickets

**Comment by Mell-A** [comment]
- collect NDVI images from GeoServer for given area and date range
- create time series visualization
- add statistics about the time series in dashboard manner

**Comment by JudithDekkers** [comment]
I created 3 new tickets for this and will close this item
